import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex.raw('TRUNCATE TABLE gymGrades RESTART IDENTITY CASCADE');

  // Inserts seed entries

  await knex('gymGrades').insert([
    // 1, Arête (By Upwall) (TODO: Not so sure, need to check)
    { gymId: 1, name: '1', order: 1 },
    { gymId: 1, name: '2', order: 2 },
    { gymId: 1, name: '3', order: 3 },
    { gymId: 1, name: '4', order: 4 },
    { gymId: 1, name: '5', order: 5 },
    { gymId: 1, name: '6', order: 6 },
    { gymId: 1, name: '7', order: 7 },
    { gymId: 1, name: '8', order: 8 },
    { gymId: 1, name: '9', order: 9 },
    { gymId: 1, name: '10', order: 10 },
    { gymId: 1, name: '11', order: 11 },
    { gymId: 1, name: '12', order: 12 },
    { gymId: 1, name: 'Wildcard', order: 13 },
    // 2, Ark Bloc
    { gymId: 2, name: '1', order: 1 },
    { gymId: 2, name: '2', order: 2 },
    { gymId: 2, name: '3', order: 3 },
    { gymId: 2, name: '4', order: 4 },
    { gymId: 2, name: '5', order: 5 },
    { gymId: 2, name: '6', order: 6 },
    { gymId: 2, name: '7', order: 7 },
    { gymId: 2, name: '8', order: 8 },
    { gymId: 2, name: '9', order: 9 },
    { gymId: 2, name: '10', order: 10 },
    { gymId: 2, name: '11', order: 11 },
    { gymId: 2, name: '12', order: 12 },
    { gymId: 2, name: 'Wildcard', order: 13 },
    // 3, b8A
    { gymId: 3, name: '1', order: 1 },
    { gymId: 3, name: '2', order: 2 },
    { gymId: 3, name: '3', order: 3 },
    { gymId: 3, name: '4', order: 4 },
    { gymId: 3, name: '5', order: 5 },
    { gymId: 3, name: '6', order: 6 },
    { gymId: 3, name: '7', order: 7 },
    { gymId: 3, name: '8', order: 8 },
    { gymId: 3, name: '9', order: 9 },
    { gymId: 3, name: '10', order: 10 },
    { gymId: 3, name: 'Wildcard', order: 11 },
    // 4, BFF Climb (Bukit Timah)
    { gymId: 4, name: '1', order: 1 },
    { gymId: 4, name: '2', order: 2 },
    { gymId: 4, name: '3', order: 3 },
    { gymId: 4, name: '4', order: 4 },
    { gymId: 4, name: '5', order: 5 },
    { gymId: 4, name: '6', order: 6 },
    { gymId: 4, name: '7', order: 7 },
    { gymId: 4, name: '8', order: 8 },
    { gymId: 4, name: '9', order: 9 },
    { gymId: 4, name: '10', order: 10 },
    { gymId: 4, name: '11', order: 11 },
    { gymId: 4, name: '12', order: 12 },
    { gymId: 4, name: 'Wildcard', order: 13 },
    // 5, BFF Climb (Bendemeer)
    { gymId: 5, name: '1', order: 1 },
    { gymId: 5, name: '2', order: 2 },
    { gymId: 5, name: '3', order: 3 },
    { gymId: 5, name: '4', order: 4 },
    { gymId: 5, name: '5', order: 5 },
    { gymId: 5, name: '6', order: 6 },
    { gymId: 5, name: '7', order: 7 },
    { gymId: 5, name: '8', order: 8 },
    { gymId: 5, name: '9', order: 9 },
    { gymId: 5, name: '10', order: 10 },
    { gymId: 5, name: '11', order: 11 },
    { gymId: 5, name: '12', order: 12 },
    { gymId: 5, name: 'Wildcard', order: 13 },
    // 6, Boruda
    { gymId: 6, name: '10Q', order: 1 },
    { gymId: 6, name: '9Q', order: 2 },
    { gymId: 6, name: '8Q', order: 3 },
    { gymId: 6, name: '7Q', order: 4 },
    { gymId: 6, name: '6Q', order: 5 },
    { gymId: 6, name: '5Q', order: 6 },
    { gymId: 6, name: '4Q', order: 7 },
    { gymId: 6, name: '3Q', order: 8 },
    { gymId: 6, name: '2Q', order: 9 },
    { gymId: 6, name: '1Q', order: 10 },
    { gymId: 6, name: '1D', order: 11 },
    { gymId: 6, name: '2D', order: 12 },
    { gymId: 6, name: 'Wildcard', order: 13 },
    // 7, Boulder Movement (Bugis+)
    { gymId: 7, name: 'L1', order: 1 },
    { gymId: 7, name: 'L2', order: 2 },
    { gymId: 7, name: 'L3', order: 3 },
    { gymId: 7, name: 'L4', order: 4 },
    { gymId: 7, name: 'L5', order: 5 },
    { gymId: 7, name: 'L6', order: 6 },
    { gymId: 7, name: 'L7', order: 7 },
    { gymId: 7, name: 'L8', order: 8 },
    { gymId: 7, name: 'L9', order: 9 },
    { gymId: 7, name: 'L10', order: 10 },
    { gymId: 7, name: 'L11', order: 11 },
    { gymId: 7, name: 'L13', order: 13 },
    { gymId: 7, name: 'L14', order: 14 },
    { gymId: 7, name: 'L15', order: 15 },
    { gymId: 7, name: 'L16', order: 16 },
    { gymId: 7, name: 'L17', order: 17 },
    { gymId: 7, name: 'L18', order: 18 },
    { gymId: 7, name: 'L19', order: 19 },
    { gymId: 7, name: 'L20', order: 20 },
    { gymId: 7, name: 'F1', order: 21 },
    { gymId: 7, name: 'F2', order: 22 },
    { gymId: 7, name: 'F3', order: 23 },
    { gymId: 7, name: 'F4', order: 24 },
    { gymId: 7, name: 'F5', order: 25 },
    { gymId: 7, name: 'Wildcard', order: 26 },
    // 8, Boulder Movement (OUE Downtown)
    { gymId: 8, name: 'L1', order: 1 },
    { gymId: 8, name: 'L2', order: 2 },
    { gymId: 8, name: 'L3', order: 3 },
    { gymId: 8, name: 'L4', order: 4 },
    { gymId: 8, name: 'L5', order: 5 },
    { gymId: 8, name: 'L6', order: 6 },
    { gymId: 8, name: 'L7', order: 7 },
    { gymId: 8, name: 'L8', order: 8 },
    { gymId: 8, name: 'L9', order: 9 },
    { gymId: 8, name: 'L10', order: 10 },
    { gymId: 8, name: 'L11', order: 11 },
    { gymId: 8, name: 'L13', order: 13 },
    { gymId: 8, name: 'L14', order: 14 },
    { gymId: 8, name: 'L15', order: 15 },
    { gymId: 8, name: 'L16', order: 16 },
    { gymId: 8, name: 'L17', order: 17 },
    { gymId: 8, name: 'L18', order: 18 },
    { gymId: 8, name: 'L19', order: 19 },
    { gymId: 8, name: 'L20', order: 20 },
    { gymId: 8, name: 'F1', order: 21 },
    { gymId: 8, name: 'F2', order: 22 },
    { gymId: 8, name: 'F3', order: 23 },
    { gymId: 8, name: 'F4', order: 24 },
    { gymId: 8, name: 'F5', order: 25 },
    { gymId: 8, name: 'Wildcard', order: 26 },
    // 9, Boulder Movement (Suntec City Mall)
    { gymId: 9, name: 'L1', order: 1 },
    { gymId: 9, name: 'L2', order: 2 },
    { gymId: 9, name: 'L3', order: 3 },
    { gymId: 9, name: 'L4', order: 4 },
    { gymId: 9, name: 'L5', order: 5 },
    { gymId: 9, name: 'L6', order: 6 },
    { gymId: 9, name: 'L7', order: 7 },
    { gymId: 9, name: 'L8', order: 8 },
    { gymId: 9, name: 'L9', order: 9 },
    { gymId: 9, name: 'L10', order: 10 },
    { gymId: 9, name: 'L11', order: 11 },
    { gymId: 9, name: 'L13', order: 13 },
    { gymId: 9, name: 'L14', order: 14 },
    { gymId: 9, name: 'L15', order: 15 },
    { gymId: 9, name: 'L16', order: 16 },
    { gymId: 9, name: 'L17', order: 17 },
    { gymId: 9, name: 'L18', order: 18 },
    { gymId: 9, name: 'L19', order: 19 },
    { gymId: 9, name: 'L20', order: 20 },
    { gymId: 9, name: 'F1', order: 21 },
    { gymId: 9, name: 'F2', order: 22 },
    { gymId: 9, name: 'F3', order: 23 },
    { gymId: 9, name: 'F4', order: 24 },
    { gymId: 9, name: 'F5', order: 25 },
    { gymId: 9, name: 'Wildcard', order: 26 },
    // 10, Boulder Movement (Tai Seng)
    { gymId: 10, name: 'L1', order: 1 },
    { gymId: 10, name: 'L2', order: 2 },
    { gymId: 10, name: 'L3', order: 3 },
    { gymId: 10, name: 'L4', order: 4 },
    { gymId: 10, name: 'L5', order: 5 },
    { gymId: 10, name: 'L6', order: 6 },
    { gymId: 10, name: 'L7', order: 7 },
    { gymId: 10, name: 'L8', order: 8 },
    { gymId: 10, name: 'L9', order: 9 },
    { gymId: 10, name: 'L10', order: 10 },
    { gymId: 10, name: 'L11', order: 11 },
    { gymId: 10, name: 'L13', order: 13 },
    { gymId: 10, name: 'L14', order: 14 },
    { gymId: 10, name: 'L15', order: 15 },
    { gymId: 10, name: 'L16', order: 16 },
    { gymId: 10, name: 'L17', order: 17 },
    { gymId: 10, name: 'L18', order: 18 },
    { gymId: 10, name: 'L19', order: 19 },
    { gymId: 10, name: 'L20', order: 20 },
    { gymId: 10, name: 'F1', order: 21 },
    { gymId: 10, name: 'F2', order: 22 },
    { gymId: 10, name: 'F3', order: 23 },
    { gymId: 10, name: 'F4', order: 24 },
    { gymId: 10, name: 'F5', order: 25 },
    { gymId: 10, name: 'Wildcard', order: 26 },
    // 11, Boulder Movement (Tekka Place)
    { gymId: 11, name: 'L1', order: 1 },
    { gymId: 11, name: 'L2', order: 2 },
    { gymId: 11, name: 'L3', order: 3 },
    { gymId: 11, name: 'L4', order: 4 },
    { gymId: 11, name: 'L5', order: 5 },
    { gymId: 11, name: 'L6', order: 6 },
    { gymId: 11, name: 'L7', order: 7 },
    { gymId: 11, name: 'L8', order: 8 },
    { gymId: 11, name: 'L9', order: 9 },
    { gymId: 11, name: 'L10', order: 10 },
    { gymId: 11, name: 'L11', order: 11 },
    { gymId: 11, name: 'L13', order: 13 },
    { gymId: 11, name: 'L14', order: 14 },
    { gymId: 11, name: 'L15', order: 15 },
    { gymId: 11, name: 'L16', order: 16 },
    { gymId: 11, name: 'L17', order: 17 },
    { gymId: 11, name: 'L18', order: 18 },
    { gymId: 11, name: 'L19', order: 19 },
    { gymId: 11, name: 'L20', order: 20 },
    { gymId: 11, name: 'F1', order: 21 },
    { gymId: 11, name: 'F2', order: 22 },
    { gymId: 11, name: 'F3', order: 23 },
    { gymId: 11, name: 'F4', order: 24 },
    { gymId: 11, name: 'F5', order: 25 },
    { gymId: 11, name: 'Wildcard', order: 26 },
    // 12, Boulder+ (Aperia Mall)
    { gymId: 12, name: 'White', order: 1 },
    { gymId: 12, name: 'Yellow', order: 2 },
    { gymId: 12, name: 'Red', order: 3 },
    { gymId: 12, name: 'Blue', order: 4 },
    { gymId: 12, name: 'Purple', order: 5 },
    { gymId: 12, name: 'Green', order: 6 },
    { gymId: 12, name: 'Pink', order: 7 },
    { gymId: 12, name: 'Wildcard', order: 8 },
    // 13, Boulder+ (The Chevrons)
    { gymId: 13, name: 'White', order: 1 },
    { gymId: 13, name: 'Yellow', order: 2 },
    { gymId: 13, name: 'Red', order: 3 },
    { gymId: 13, name: 'Blue', order: 4 },
    { gymId: 13, name: 'Purple', order: 5 },
    { gymId: 13, name: 'Green', order: 6 },
    { gymId: 13, name: 'Pink', order: 7 },
    { gymId: 13, name: 'Wildcard', order: 8 },
    // 14, Boulder Planet (Sembawang)
    { gymId: 14, name: '1', order: 1 },
    { gymId: 14, name: '2', order: 2 },
    { gymId: 14, name: '3', order: 3 },
    { gymId: 14, name: '4', order: 4 },
    { gymId: 14, name: '5', order: 5 },
    { gymId: 14, name: '6', order: 6 },
    { gymId: 14, name: '7', order: 7 },
    { gymId: 14, name: '8', order: 8 },
    { gymId: 14, name: '9', order: 9 },
    { gymId: 14, name: '10', order: 10 },
    { gymId: 14, name: '11', order: 11 },
    { gymId: 14, name: '12', order: 12 },
    { gymId: 14, name: 'Wildcard', order: 13 },
    // 15, Boulder World (SingPost)
    { gymId: 15, name: 'L1', order: 1 },
    { gymId: 15, name: 'L2', order: 2 },
    { gymId: 15, name: 'L3', order: 3 },
    { gymId: 15, name: 'L4', order: 4 },
    { gymId: 15, name: 'L5', order: 5 },
    { gymId: 15, name: 'L6', order: 6 },
    { gymId: 15, name: 'L7', order: 7 },
    { gymId: 15, name: 'L8', order: 8 },
    { gymId: 15, name: 'Wildcard', order: 9 },
    // 16, Boulder World (Paragon)
    { gymId: 16, name: 'L1', order: 1 },
    { gymId: 16, name: 'L2', order: 2 },
    { gymId: 16, name: 'L3', order: 3 },
    { gymId: 16, name: 'L4', order: 4 },
    { gymId: 16, name: 'L5', order: 5 },
    { gymId: 16, name: 'L6', order: 6 },
    { gymId: 16, name: 'L7', order: 7 },
    { gymId: 16, name: 'L8', order: 8 },
    { gymId: 16, name: 'Wildcard', order: 9 },
    // 17, Climb Central (Katong)
    { gymId: 17, name: '0 Pie', order: 1 },
    { gymId: 17, name: '1 Pie', order: 2 },
    { gymId: 17, name: '2 Pie', order: 3 },
    { gymId: 17, name: '3 Pie', order: 4 },
    { gymId: 17, name: '4 Pie', order: 5 },
    { gymId: 17, name: '5 Pie', order: 6 },
    { gymId: 17, name: '6 Pie', order: 7 },
    { gymId: 17, name: 'Wildcard', order: 8 },
    // 18, Climb Central (Novena)
    { gymId: 18, name: '0 Pie', order: 1 },
    { gymId: 18, name: '1 Pie', order: 2 },
    { gymId: 18, name: '2 Pie', order: 3 },
    { gymId: 18, name: '3 Pie', order: 4 },
    { gymId: 18, name: '4 Pie', order: 5 },
    { gymId: 18, name: '5 Pie', order: 6 },
    { gymId: 18, name: '6 Pie', order: 7 },
    { gymId: 18, name: 'Wildcard', order: 8 },
    // 19, Climb Central (Sports Hub)
    { gymId: 19, name: '0 Pie', order: 1 },
    { gymId: 19, name: '1 Pie', order: 2 },
    { gymId: 19, name: '2 Pie', order: 3 },
    { gymId: 19, name: '3 Pie', order: 4 },
    { gymId: 19, name: '4 Pie', order: 5 },
    { gymId: 19, name: '5 Pie', order: 6 },
    { gymId: 19, name: '6 Pie', order: 7 },
    { gymId: 19, name: 'Wildcard', order: 8 },
    // 20, Climb Central (Funan)
    { gymId: 20, name: '0 Pie', order: 1 },
    { gymId: 20, name: '1 Pie', order: 2 },
    { gymId: 20, name: '2 Pie', order: 3 },
    { gymId: 20, name: '3 Pie', order: 4 },
    { gymId: 20, name: '4 Pie', order: 5 },
    { gymId: 20, name: '5 Pie', order: 6 },
    { gymId: 20, name: '6 Pie', order: 7 },
    { gymId: 20, name: 'Wildcard', order: 8 },
    // 21, Fit Bloc (Depot Heights)
    { gymId: 21, name: '0 Bar', order: 1 },
    { gymId: 21, name: '1 Bar', order: 2 },
    { gymId: 21, name: '2 Bar', order: 3 },
    { gymId: 21, name: '3 Bar', order: 4 },
    { gymId: 21, name: '4 Bar', order: 5 },
    { gymId: 21, name: '5 Bar', order: 6 },
    { gymId: 21, name: '6 Bar', order: 7 },
    { gymId: 21, name: '7 Bar', order: 8 },
    { gymId: 21, name: '8 Bar', order: 9 },
    { gymId: 21, name: 'Supercharged', order: 10 },
    { gymId: 21, name: 'Wildcard', order: 11 },
    // 22, Fit Bloc (Kent Ridge)
    { gymId: 22, name: '0 Bar', order: 1 },
    { gymId: 22, name: '1 Bar', order: 2 },
    { gymId: 22, name: '2 Bar', order: 3 },
    { gymId: 22, name: '3 Bar', order: 4 },
    { gymId: 22, name: '4 Bar', order: 5 },
    { gymId: 22, name: '5 Bar', order: 6 },
    { gymId: 22, name: '6 Bar', order: 7 },
    { gymId: 22, name: '7 Bar', order: 8 },
    { gymId: 22, name: '8 Bar', order: 9 },
    { gymId: 21, name: 'Supercharged', order: 10 },
    { gymId: 21, name: 'Wildcard', order: 11 },
    // 23, Ground Up Climbing
    { gymId: 23, name: 'V0', order: 1 },
    { gymId: 23, name: 'V1', order: 2 },
    { gymId: 23, name: 'V2', order: 3 },
    { gymId: 23, name: 'V3', order: 4 },
    { gymId: 23, name: 'V4', order: 5 },
    { gymId: 23, name: 'V5', order: 6 },
    { gymId: 23, name: 'V6', order: 7 },
    { gymId: 23, name: 'V7', order: 8 },
    { gymId: 23, name: 'V8', order: 9 },
    { gymId: 23, name: '5c', order: 10 },
    { gymId: 23, name: '6a', order: 11 },
    { gymId: 23, name: '6a+', order: 12 },
    { gymId: 23, name: '6b', order: 13 },
    { gymId: 23, name: '6b+', order: 14 },
    { gymId: 23, name: '6c', order: 15 },
    { gymId: 23, name: '6c+', order: 16 },
    { gymId: 23, name: '7a', order: 17 },
    { gymId: 23, name: '7a+', order: 18 },
    { gymId: 23, name: '7b', order: 19 },
    { gymId: 23, name: '7b+', order: 20 },
    { gymId: 23, name: '7c', order: 21 },
    { gymId: 23, name: '7c+', order: 22 },
    { gymId: 23, name: '8a', order: 23 },
    { gymId: 23, name: '8a+', order: 24 },
    { gymId: 23, name: '8b', order: 25 },
    { gymId: 23, name: '8b+', order: 26 },
    { gymId: 23, name: '8c', order: 27 },
    { gymId: 23, name: 'Wildcard', order: 28 },
    // 24, Kinetics
    { gymId: 24, name: 'White', order: 1 },
    { gymId: 24, name: 'Red', order: 2 },
    { gymId: 24, name: 'Blue', order: 3 },
    { gymId: 24, name: 'Yellow', order: 4 },
    { gymId: 24, name: 'Green', order: 5 },
    { gymId: 24, name: 'Black', order: 6 },
    { gymId: 24, name: 'Wildcard', order: 7 },
    // 25, Lighthouse Climbing
    { gymId: 25, name: '1', order: 1 },
    { gymId: 25, name: '2', order: 2 },
    { gymId: 25, name: '3', order: 3 },
    { gymId: 25, name: '4', order: 4 },
    { gymId: 25, name: '5', order: 5 },
    { gymId: 25, name: '6', order: 6 },
    { gymId: 25, name: '7', order: 7 },
    { gymId: 25, name: '8', order: 8 },
    { gymId: 25, name: '9', order: 9 },
    { gymId: 25, name: 'Wildcard', order: 10 },
    // 26, Origin Boulderys
    { gymId: 26, name: '1', order: 1 },
    { gymId: 26, name: '2', order: 2 },
    { gymId: 26, name: '3', order: 3 },
    { gymId: 26, name: '4', order: 4 },
    { gymId: 26, name: '5', order: 5 },
    { gymId: 26, name: '6', order: 6 },
    { gymId: 26, name: '7', order: 7 },
    { gymId: 26, name: '8', order: 8 },
    { gymId: 26, name: 'Wildcard', order: 9 },
    // 27, OYEYO Bouldering Home
    { gymId: 27, name: 'White', order: 1 },
    { gymId: 27, name: 'Yellow', order: 2 },
    { gymId: 27, name: 'Pink', order: 3 },
    { gymId: 27, name: 'Red', order: 4 },
    { gymId: 27, name: 'Green', order: 5 },
    { gymId: 27, name: 'Wilcard', order: 6 },
    // 28, Project Send (TODO: Not so sure, need to check)
    { gymId: 28, name: '1', order: 1 },
    { gymId: 28, name: '2', order: 2 },
    { gymId: 28, name: '3', order: 3 },
    { gymId: 28, name: '4', order: 4 },
    { gymId: 28, name: '5', order: 5 },
    { gymId: 28, name: '6', order: 6 },
    { gymId: 28, name: '7', order: 7 },
    { gymId: 28, name: '8', order: 8 },
    { gymId: 28, name: '9', order: 9 },
    { gymId: 28, name: '10', order: 10 },
    { gymId: 28, name: '11', order: 11 },
    { gymId: 28, name: '12', order: 12 },
    { gymId: 28, name: 'Wildcard', order: 15 },
    // 29, T-Hall
    { gymId: 29, name: '5c', order: 1 },
    { gymId: 29, name: '6a', order: 2 },
    { gymId: 29, name: '6a+', order: 3 },
    { gymId: 29, name: '6b', order: 4 },
    { gymId: 29, name: '6b+', order: 5 },
    { gymId: 29, name: '6c', order: 6 },
    { gymId: 29, name: '6c+', order: 7 },
    { gymId: 29, name: '7a', order: 8 },
    { gymId: 29, name: '7a+', order: 9 },
    { gymId: 29, name: '7b', order: 10 },
    { gymId: 29, name: '7b+', order: 11 },
    { gymId: 29, name: '7c', order: 12 },
    { gymId: 29, name: '7c+', order: 13 },
    { gymId: 29, name: '8a', order: 14 },
    { gymId: 29, name: 'Wildcard', order: 15 },
    // 30, The Rock School (Our Tampines Hub)
    { gymId: 30, name: '5c', order: 1 },
    { gymId: 30, name: '6a', order: 2 },
    { gymId: 30, name: '6a+', order: 3 },
    { gymId: 30, name: '6b', order: 4 },
    { gymId: 30, name: '6b+', order: 5 },
    { gymId: 30, name: '6c', order: 6 },
    { gymId: 30, name: '6c+', order: 7 },
    { gymId: 30, name: '7a', order: 8 },
    { gymId: 30, name: '7a+', order: 9 },
    { gymId: 30, name: '7b', order: 10 },
    { gymId: 30, name: '7b+', order: 11 },
    { gymId: 30, name: '7c', order: 12 },
    { gymId: 30, name: '7c+', order: 13 },
    { gymId: 30, name: '8a', order: 14 },
    { gymId: 30, name: 'Wildcard', order: 15 },
    // 31, Up Wall Climbing (TODO: Not so sure, need to check)
    { gymId: 31, name: '5c', order: 1 },
    { gymId: 31, name: '6a', order: 2 },
    { gymId: 31, name: '6a+', order: 3 },
    { gymId: 31, name: '6b', order: 4 },
    { gymId: 31, name: '6b+', order: 5 },
    { gymId: 31, name: '6c', order: 6 },
    { gymId: 31, name: '6c+', order: 7 },
    { gymId: 31, name: '7a', order: 8 },
    { gymId: 31, name: '7a+', order: 9 },
    { gymId: 31, name: '7b', order: 10 },
    { gymId: 31, name: '7b+', order: 11 },
    { gymId: 31, name: '7c', order: 12 },
    { gymId: 31, name: '7c+', order: 13 },
    { gymId: 31, name: '8a', order: 14 },
    { gymId: 31, name: 'Wildcard', order: 15 },
    // 32, Z-Vertigo Boulder Gym
    { gymId: 32, name: '1', order: 1 },
    { gymId: 32, name: '2', order: 2 },
    { gymId: 32, name: '3', order: 3 },
    { gymId: 32, name: '4', order: 4 },
    { gymId: 32, name: '5', order: 5 },
    { gymId: 32, name: '6', order: 6 },
    { gymId: 32, name: '7', order: 7 },
    { gymId: 32, name: 'Wilcard', order: 8 },
  ]);
}
