import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  const data = [
    {
      name: 'Arête (By Upwall)',
      shortName: 'Arête',
      permanentlyClosed: false,
      id: 1,
      gymGroupId: 18,
      area: 'Expo',
      address:
        '5 Changi Business Park Central 1, #02-14/15/16, Singapore 486038',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/arete.climbing?igshid=NDk5N2NlZjQ=',
      website: 'https://upwallclimbing.sg/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Ark Bloc',
      shortName: 'Ark Bloc',
      permanentlyClosed: false,
      id: 2,
      gymGroupId: 1,
      area: 'Punggol/Tampines',
      address: 'Ark Bloc Punggol, 6 Tebing Lane, #01-05, Singapore 828835',
      passSharing:
        'Passholder does not need to present; Account passes shared on the spot',
      socialUrl: 'https://instagram.com/arkbloc?igshid=NDk5N2NlZjQ=',
      website: 'https://arkbloc.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'b8A',
      shortName: 'b8A',
      permanentlyClosed: false,
      id: 3,
      gymGroupId: 2,
      area: 'Tampines West',
      address:
        '03-06, 6 Tampines Street 92, yo:HA Commercial @ Tampines, Singapore 528893',
      passSharing:
        'Passholder does not need to present; Account passes shared on the spot',
      socialUrl: 'https://instagram.com/b8a.sg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.b8a.sg/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'BFF Climb (Bukit Timah)',
      shortName: 'BFF (Bkt Timah)',
      permanentlyClosed: false,
      id: 4,
      gymGroupId: 3,
      area: 'King Albert Park',
      address: '896 Dunearn Rd, #02-01D, Singapore 589472',
      passSharing:
        'Passholder does not need to present; Account passes shared on the spot',
      socialUrl:
        'https://instagram.com/bffclimb.boulderzone?igshid=NDk5N2NlZjQ=',
      website: 'https://bffclimb.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'BFF Climb (Bendemeer)',
      shortName: 'BFF (Bendmr)',
      permanentlyClosed: false,
      id: 5,
      gymGroupId: 3,
      area: 'Bendemeer',
      address: 'CT Hub, 2 Kallang Avenue, #01-20, Singapore 339407',
      passSharing:
        'Passholder does not need to present; Account passes shared on the spot',
      socialUrl:
        'https://instagram.com/bffclimb.boulderzone?igshid=NDk5N2NlZjQ=',
      website: 'https://bffclimb.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: true,
    },
    {
      name: 'boruda',
      shortName: 'boruda',
      permanentlyClosed: false,
      id: 6,
      gymGroupId: 4,
      area: 'Labrador Park',
      address: '991A Alexandra Rd, Singapore 119969',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/boruda.sg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boruda.sg/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder Movement (Bugis)',
      shortName: 'BM (Bugis)',
      permanentlyClosed: false,
      id: 7,
      gymGroupId: 5,
      area: 'Bugis',
      address: '201 Victoria Street #05-07, Bugis+, Singapore 188067',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/bouldermovementsg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderm.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder Movement (Downtown)',
      shortName: 'BM (OUE)',
      permanentlyClosed: false,
      id: 8,
      gymGroupId: 5,
      area: 'Downtown',
      address: '6A Shenton Way #B1-03 Downtown Gallery, 068815',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/bouldermovementsg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderm.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder Movement (Suntec)',
      shortName: 'BM (Suntec)',
      permanentlyClosed: false,
      id: 9,
      gymGroupId: 5,
      area: 'Suntec',
      address:
        '3 Temasek Boulevard, #01-484/85/86, Suntec City Mall (North Wing), Tower One, Singapore 038983',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/bouldermovementsg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderm.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder Movement (Tai Seng)',
      shortName: 'BM (Tai Seng)',
      permanentlyClosed: false,
      id: 10,
      gymGroupId: 5,
      area: 'Tai Seng',
      address: '18 Tai Seng St, #01-09, Singapore 539775',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/bouldermovementsg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderm.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder Movement (Rochor)',
      shortName: 'BM (Tekka)',
      permanentlyClosed: false,
      id: 11,
      gymGroupId: 5,
      area: 'Rochor',
      address: '2 Serangoon Rd, #02-12 Tekka Place, Singapore 218227',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/bouldermovementsg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderm.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder+ (Aperia Mall)',
      shortName: 'B+ (Aperia)',
      permanentlyClosed: false,
      id: 12,
      gymGroupId: 6,
      area: 'Lavender',
      address: '12 Kallang Ave, #03-17, The Aperia Mall, Singapore 339511',
      passSharing: 'Passholder must be present and checked in',
      socialUrl: 'https://instagram.com/boulder_plus?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderplusclimbing.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder+ (The Chevrons)',
      shortName: 'B+ (Chevrons)',
      permanentlyClosed: false,
      id: 13,
      gymGroupId: 6,
      area: 'Jurong East',
      address: '48 Boon Lay Way, 04-01 The Chevrons, Singapore 609961',
      passSharing: 'Passholder must be present and checked in',
      socialUrl: 'https://instagram.com/boulder_plus?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderplusclimbing.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder Planet (Sembawang)',
      shortName: 'BP (Semb)',
      permanentlyClosed: false,
      id: 14,
      gymGroupId: 4,
      area: 'Canberra (Sembwanag Mall)',
      address:
        '604 Sembawang Road, Sembawang Shopping Centre, #B1, 22/23, 758459',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/boulderplanet.sg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderplanet.sg/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder World (SingPost)',
      shortName: 'BW (SingPost)',
      permanentlyClosed: true,
      id: 15,
      gymGroupId: 7,
      area: 'Paya Lebar',
      address:
        '10 Eunos Rd 8, #01-205 SingPost Centre (Enrichment Zone, Singapore 408600',
      passSharing: 'Passholder must be present and checked in',
      socialUrl: 'https://instagram.com/boulderworldsg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderworld.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder World (Paragon)',
      shortName: 'BW (Paragon)',
      permanentlyClosed: false,
      id: 16,
      gymGroupId: 7,
      area: 'Orchard',
      address:
        '290 Orchard Rd, #06-25/26, Paragon Shopping Centre, Singapore 238859',
      passSharing: 'Passholder must be present and checked in',
      socialUrl: 'https://instagram.com/boulderworldsg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderworld.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Climb Central (Katong)',
      shortName: 'CC (Katong)',
      permanentlyClosed: false,
      id: 17,
      gymGroupId: 8,
      area: 'Katong',
      address: 'i12 Katong, 112 East Coast Road, #04-01/02, Singapore 428802',
      passSharing: 'Passholder must be present and checked in',
      socialUrl: 'https://instagram.com/climbcentral?igshid=NDk5N2NlZjQ=',
      website: 'https://www.climbcentral.sg/',
      lead: true,
      boulder: false,
      topRope: true,
      autoBelay: true,
    },
    {
      name: 'Climb Central (Novena)',
      shortName: 'CC (Novena)',
      permanentlyClosed: false,
      id: 18,
      gymGroupId: 8,
      area: 'Novena',
      address: 'Novena Square, 238 Thomson Rd, #03-23/25, Singapore 307683',
      passSharing: 'Passholder must be present and checked in',
      socialUrl: 'https://instagram.com/climbcentral?igshid=NDk5N2NlZjQ=',
      website: 'https://www.climbcentral.sg/',
      lead: false,
      boulder: true,
      topRope: true,
      autoBelay: true,
    },
    {
      name: 'Climb Central (Sports Hub)',
      shortName: 'CC (Sports Hub)',
      permanentlyClosed: false,
      id: 19,
      gymGroupId: 8,
      area: 'Kallang',
      address: 'Kallang Wave Mall, 1 Stadium Place, #B1-01, Singapore 397628',
      passSharing: 'Passholder must be present and checked in',
      socialUrl: 'https://instagram.com/climbcentral?igshid=NDk5N2NlZjQ=',
      website: 'https://www.climbcentral.sg/',
      lead: true,
      boulder: true,
      topRope: true,
      autoBelay: true,
    },
    {
      name: 'Climb Central (Funan)',
      shortName: 'CC (Funan)',
      permanentlyClosed: false,
      id: 20,
      gymGroupId: 8,
      area: 'City Hall',
      address: 'Funan Mall, 107 North Bridge Road, #B2-19/21, Singapore 179105',
      passSharing: 'Passholder must be present and checked in',
      socialUrl: 'https://instagram.com/climbcentral?igshid=NDk5N2NlZjQ=',
      website: 'https://www.climbcentral.sg/',
      lead: true,
      boulder: true,
      topRope: true,
      autoBelay: true,
    },
    {
      name: 'FitBloc (Depot Heights)',
      shortName: 'FitBloc (DH)',
      permanentlyClosed: false,
      id: 21,
      gymGroupId: 9,
      area: 'Redhill/Telok Blangah',
      address:
        '108 Depot Rd, #02-01 Depot Heights Shopping Centre, Singapore 100108',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/fitbloc?igshid=NDk5N2NlZjQ=',
      website: 'https://fitbloc.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: true,
    },
    {
      name: 'FitBloc (Kent Ridge)',
      shortName: 'FitBloc (KR)',
      permanentlyClosed: false,
      id: 22,
      gymGroupId: 9,
      area: 'Kent Ridge',
      address: '87 Science Park Dr, #03-02 The Oasis, Singapore 118260',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/fitbloc?igshid=NDk5N2NlZjQ=',
      website: 'https://fitbloc.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: true,
    },
    {
      name: 'Ground Up',
      shortName: 'GU',
      permanentlyClosed: false,
      id: 23,
      gymGroupId: 10,
      area: 'Farrer Park',
      address: '60 Tessensohn Road, CSC@Tessensohn, Level 2, Singapore 217664',
      passSharing: '',
      socialUrl: 'https://instagram.com/groundupsg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.groundupsg.com/',
      lead: true,
      boulder: true,
      topRope: true,
      autoBelay: true,
    },
    {
      name: 'Kinetics',
      shortName: 'Kinetics',
      permanentlyClosed: false,
      id: 24,
      gymGroupId: 11,
      area: 'Farrer Park',
      address: '511 Serangoon Rd, Singapore 218153',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/kineticsclimbing?igshid=NDk5N2NlZjQ=',
      website: 'https://www.kineticsclimbing.com.sg/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Lighthouse',
      shortName: 'Lighthouse',
      permanentlyClosed: false,
      id: 25,
      gymGroupId: 12,
      area: 'Pasir Panjang',
      address: '44 Pasir Panjang Road #B-02, 118504',
      passSharing:
        'Passholder does not need to present; Account passes shared on the spot',
      socialUrl:
        'https://instagram.com/lighthouse.climbing?igshid=NDk5N2NlZjQ=',
      website: 'https://www.lighthouseclimbing.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Origin Boulder',
      shortName: 'Origin',
      permanentlyClosed: false,
      id: 26,
      gymGroupId: 13,
      area: 'Telok Ayer',
      address: '18 Cross Street, Cross Street Exchange B1-117 & B1-118, 048423',
      passSharing:
        'Passholder does not need to present; Account passes shared on the spot',
      socialUrl: 'https://instagram.com/originboulder?igshid=NDk5N2NlZjQ=',
      website: 'https://originboulder.sg/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'OYEYO',
      shortName: 'OYEYO',
      permanentlyClosed: false,
      id: 27,
      gymGroupId: 14,
      area: 'Little India',
      address: '148 Mackenzie Rd, Singapore 228724',
      passSharing:
        'Passholder does not need to present; Account passes shared on the spot',
      socialUrl: 'https://instagram.com/oyeyoboulderhome?igshid=NDk5N2NlZjQ=',
      website: 'https://oyeyoboulderhome.com/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Project Send',
      shortName: 'Project Send',
      permanentlyClosed: false,
      id: 28,
      gymGroupId: 15,
      area: 'Esplanade',
      address: '8 Raffles Ave., #02-29 Esplanade Mall, Singapore 039802',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/projectsend.sg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.projectsend.co/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'T-Hall',
      shortName: 'T-Hall',
      permanentlyClosed: false,
      id: 29,
      gymGroupId: 16,
      area: 'Lavender',
      address: '464 Crawford Ln, #01-464, Singapore 190464',
      passSharing: '',
      socialUrl: 'https://instagram.com/thall.sg?igshid=NDk5N2NlZjQ=',
      website: 'https://t-hall.sg/',
      lead: true,
      boulder: true,
      topRope: true,
      autoBelay: true,
    },
    {
      name: 'The Rock School (Our Tampines Hub)',
      shortName: 'TRS',
      permanentlyClosed: false,
      id: 30,
      gymGroupId: 17,
      area: 'Tampines',
      address: 'Our Tampines Hub, 1 Tampines Walk, #02-81, Singapore 528523',
      passSharing:
        'Passholder does not need to present; Account passes shared on the spot',
      socialUrl: 'https://instagram.com/therockschool?igshid=NDk5N2NlZjQ=',
      website: 'https://www.therockschool.sg/',
      lead: true,
      boulder: true,
      topRope: true,
      autoBelay: true,
    },
    {
      name: 'Upwall',
      shortName: 'Upwall',
      permanentlyClosed: false,
      id: 31,
      gymGroupId: 18,
      area: 'Downtown East',
      address: '1 Pasir Ris Close, E!Hub@Downtown East, #01-105, 519599',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/upwallclimbing?igshid=NDk5N2NlZjQ=',
      website: 'https://upwallclimbing.sg/',
      lead: true,
      boulder: true,
      topRope: true,
      autoBelay: true,
    },
    {
      name: 'Z-Vertigo',
      shortName: 'Z-Vertigo',
      permanentlyClosed: false,
      id: 32,
      gymGroupId: 19,
      area: 'Beauty World ',
      address: '170 Upper Bukit Timah Rd, B2-20B Z-Vertigo Boulder Gym, 588179',
      passSharing:
        'Passholder does not need to present; Account passes shared on the spot',
      socialUrl: 'https://instagram.com/zvertigobouldergym?igshid=NDk5N2NlZjQ=',
      website: '',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Boulder Planet (Tai Seng)',
      shortName: 'BP (Tai Seng)',
      permanentlyClosed: false,
      id: 33,
      gymGroupId: 4,
      area: 'Tai Seng',
      address:
        '601 MacPherson Rd, #02-07 Grantral Mall @ MacPherson, Singapore 368242',
      passSharing:
        'Passholder does not need to be present but accounts have to be linked beforehand',
      socialUrl: 'https://instagram.com/boulderplanet.sg?igshid=NDk5N2NlZjQ=',
      website: 'https://www.boulderplanet.sg/',
      lead: false,
      boulder: true,
      topRope: false,
      autoBelay: false,
    },
    {
      name: 'Climb@T3',
      shortName: 'Climb@T3',
      permanentlyClosed: false,
      id: 39,
      gymGroupId: 17,
      area: 'Changi Airport',
      address: 'Changi Airport Terminal 3, #B3-01/02 Singapore',
      passSharing:
        "Passholder does not need to be present; either book under passholder's name, or link accounts to share passes",
      socialUrl: 'https://instagram.com/climbt3?igshid=NDk5N2NlZjQ=',
      website: 'https://www.climbt3.sg/home',
      lead: true,
      boulder: false,
      topRope: true,
      autoBelay: true,
    },
  ];

  // calling an insert on every row causes an error to be thrown when the e2e test is run:
  // error: sorry, too many clients already
  // seed 15-f01-add-gyms-passes also causes this
  // with all items in the data array, 8 tests pass before error is thrown
  // if i only use 3, 28 pass before error is thrown
  // i suspect it is due to Promise.all causing all the queries to be run in parallel, as described here
  // https://stackoverflow.com/a/48069213/7577786 in the first comment:
  // This is because Promise.all() executes all queries in parallel. To fix this, all promises must be resolved one after another. You can do this with code in this stackoverflow question
  // https://stackoverflow.com/questions/24586110/resolve-promises-one-after-another-i-e-in-sequence

  // await Promise.all(
  //   data.map(async (row) => {
  //     return knex('gyms').insert(row).where('gyms.id', row.id).onConflict('id').merge();
  //     // await knex('gyms').insert(row).where('gyms.id', row.id).onConflict('id').merge();
  //   }),
  // );

  // for loop supposedly doesn't make all the queries execute in parralel like Promise.all does
  for (const row of data) {
    await knex('gyms')
      .insert(row)
      .where('gyms.id', row.id)
      .onConflict('id')
      .merge();
  }

  // this works too as only one query is made/connection is opened
  // await knex('gyms').insert(data).onConflict('id').merge();

  // forEach, however, doesn't work
  // data.forEach(async (row) => {
  //   await knex('gyms').insert(row).where('gyms.id', row.id).onConflict('id').merge()
  // })

  await knex('gyms').update({ gymGroupId: 20 }).whereLike('name', 'Camp5%');
}
