import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex.raw('TRUNCATE TABLE passes RESTART IDENTITY');

  await knex('passes').insert([
    {
      passName: 'Single Entry',
      passGroupId: 1,
      numberOfPasses: 1,
      price: 22,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://upwallclimbing.sg/gym-entry-pass/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 1,
      numberOfPasses: 5,
      price: 100,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by contacting gym via Whatsapp',
      timeRestriction: '',
      validityPeriod: '6 months from first usage',
      infoUrl: 'https://upwallclimbing.sg/gym-entry-pass/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 1,
      numberOfPasses: 10,
      price: 180,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by contacting gym via Whatsapp',
      timeRestriction: '',
      validityPeriod: '6 months from first usage',
      infoUrl: 'https://upwallclimbing.sg/gym-entry-pass/',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 1,
      numberOfPasses: 0,
      price: 80,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://upwallclimbing.sg/gym-entry-pass/',
      remarks: '',
    },
    {
      passName: 'Adult Supervision',
      passGroupId: 1,
      numberOfPasses: 1,
      price: 10,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://upwallclimbing.sg/gym-entry-pass/',
      remarks: 'Mandatory for kids below 12 years old',
    },
    {
      passName: 'Single Entry',
      passGroupId: 2,
      numberOfPasses: 1,
      price: 28,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://arkbloc.com/#prices',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 2,
      numberOfPasses: 3,
      price: 84,
      discountedPrice: 58,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Non-shareable',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl: 'https://arkbloc.com/#prices',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 2,
      numberOfPasses: 10,
      price: 190,
      discountedPrice: 168,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://arkbloc.com/#prices',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 2,
      numberOfPasses: 0,
      price: 90,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 100,
      discountedInitiationFee: 50,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://arkbloc.com/#prices',
      remarks: '',
    },
    {
      passName: 'Adult Entry (PayNow/Cash)',
      passGroupId: 3,
      numberOfPasses: 1,
      price: 22,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'PayNow/Cash',
    },
    {
      passName: 'Adult Entry (Credit Card)',
      passGroupId: 3,
      numberOfPasses: 1,
      price: 23,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'Credit Card',
    },
    {
      passName: 'Adult Entry (Off-peak) (PayNow/Cash)',
      passGroupId: 3,
      numberOfPasses: 1,
      price: 18,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'PayNow/Cash',
    },
    {
      passName: 'Adult Entry (Off-peak) (Credit Card)',
      passGroupId: 3,
      numberOfPasses: 1,
      price: 19,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'Credit Card',
    },
    {
      passName: 'Multipass (PayNow/Cash)',
      passGroupId: 3,
      numberOfPasses: 5,
      price: 93,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy:
        'Shareable by booking for friends via Whatsapp; bringing a friend when booking online; or in-person at the counter',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'PayNow/Cash',
    },
    {
      passName: 'Multipass (Credit Card)',
      passGroupId: 3,
      numberOfPasses: 5,
      price: 97,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy:
        'Shareable by booking for friends via Whatsapp; bringing a friend when booking online; or in-person at the counter',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'Credit Card',
    },
    {
      passName: 'Multipass (PayNow/Cash)',
      passGroupId: 3,
      numberOfPasses: 10,
      price: 158,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy:
        'Shareable by booking for friends via Whatsapp; bringing a friend when booking online; or in-person at the counter',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'PayNow/Cash',
    },
    {
      passName: 'Multipass (Credit Card)',
      passGroupId: 3,
      numberOfPasses: 10,
      price: 164,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy:
        'Shareable by booking for friends via Whatsapp; bringing a friend when booking online; or in-person at the counter',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'Credit Card',
    },
    {
      passName: 'Youth Entry (PayNow/Cash)',
      passGroupId: 3,
      numberOfPasses: 1,
      price: 15,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 21',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'PayNow/Cash',
    },
    {
      passName: 'Youth Multipass (PayNow/Cash)',
      passGroupId: 3,
      numberOfPasses: 5,
      price: 68,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 21',
      sharingPolicy: 'Unshareable',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'PayNow/Cash',
    },
    {
      passName: 'Youth Multipass (Credit Card)',
      passGroupId: 3,
      numberOfPasses: 5,
      price: 72,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 21',
      sharingPolicy: 'Unshareable',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.b8a.sg/entry-passes/',
      remarks: 'Credit Card',
    },
    {
      passName: 'Youth Entry',
      passGroupId: 4,
      numberOfPasses: 1,
      price: 17.28,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 19',
      sharingPolicy: '',
      timeRestriction: 'Weekday 9.30am - 6pm, excluding Public Holidays',
      validityPeriod: '',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 4,
      numberOfPasses: 5,
      price: 118.8,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable at counter or by booking for a friend',
      timeRestriction: '',
      validityPeriod: '12 months from first use',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 4,
      numberOfPasses: 10,
      price: 205.2,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable at counter or by booking for a friend',
      timeRestriction: '',
      validityPeriod: '12 months from first use',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 4,
      numberOfPasses: 0,
      price: 140.4,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: 100,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Subscription (Off-peak)',
      passGroupId: 4,
      numberOfPasses: 0,
      price: 70.2,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: 50,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: 'Weekday 9.30am to 6pm. Excluding Public Holidays',
      validityPeriod: '',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 5,
      numberOfPasses: 1,
      price: 23.76,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 5,
      numberOfPasses: 5,
      price: 102.6,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable at counter or by booking for a friend',
      timeRestriction: '',
      validityPeriod: '12 months from first use',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 5,
      numberOfPasses: 10,
      price: 183.6,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable at counter or by booking for a friend',
      timeRestriction: '',
      validityPeriod: '12 months from first use',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 5,
      numberOfPasses: 0,
      price: 97.2,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: 100,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 6,
      numberOfPasses: 1,
      price: 27,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 6,
      numberOfPasses: 0,
      price: 108,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: 100,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://bffclimb.com/rates/',
      remarks: '',
    },
    {
      passName: 'Single Entry',
      passGroupId: 7,
      numberOfPasses: 1,
      price: 30,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderplanet.sg/rates',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 7,
      numberOfPasses: 5,
      price: 125,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by linking accounts',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.boulderplanet.sg/rates',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 7,
      numberOfPasses: 10,
      price: 200,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by linking accounts',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.boulderplanet.sg/rates',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 7,
      numberOfPasses: 4,
      price: 56,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 98,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderplanet.sg/subscription',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription',
      passGroupId: 7,
      numberOfPasses: 8,
      price: 88,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 98,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderplanet.sg/subscription',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription',
      passGroupId: 7,
      numberOfPasses: 0,
      price: 110,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 98,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderplanet.sg/subscription',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Single Entry',
      passGroupId: 8,
      numberOfPasses: 1,
      price: 30,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boruda.sg/pricing',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 8,
      numberOfPasses: 5,
      price: 125,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Share by linking accounts',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.boruda.sg/pricing',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 8,
      numberOfPasses: 10,
      price: 200,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Share by linking accounts',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.boruda.sg/pricing',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 8,
      numberOfPasses: 4,
      price: 56,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 98,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boruda.sg/pricing',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription',
      passGroupId: 8,
      numberOfPasses: 8,
      price: 88,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 98,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boruda.sg/pricing',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription',
      passGroupId: 8,
      numberOfPasses: 0,
      price: 110,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 98,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boruda.sg/pricing',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 9,
      numberOfPasses: 1,
      price: 30,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderm.com/pricing/entry',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 9,
      numberOfPasses: 5,
      price: 135,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by linking accounts or booking for a friend',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl: 'https://www.boulderm.com/pricing/entry',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 9,
      numberOfPasses: 10,
      price: 200,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by linking accounts or booking for a friend',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.boulderm.com/pricing/entry',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 9,
      numberOfPasses: 0,
      price: 118,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderm.com/pricing/membership',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription (Off-peak)',
      passGroupId: 9,
      numberOfPasses: 0,
      price: 68,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction:
        'Tue -Fri, 12.00pm to 4.30pm\nIncludes Wed 9am at Rochor\nExcludes Public Holidays',
      validityPeriod: '',
      infoUrl: 'https://www.boulderm.com/pricing/membership',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Foundation Class',
      passGroupId: 9,
      numberOfPasses: 1,
      price: 35,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl: 'https://www.boulderm.com/pricing/membership',
      remarks: '',
    },
    {
      passName: 'Foundation Class Multipass',
      passGroupId: 9,
      numberOfPasses: 5,
      price: 150,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.boulderm.com/pricing/membership',
      remarks: '',
    },
    {
      passName: 'Master Class',
      passGroupId: 9,
      numberOfPasses: 1,
      price: 80,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl: 'https://www.boulderm.com/pricing/membership',
      remarks: '',
    },
    {
      passName: 'Master Class Multipass',
      passGroupId: 9,
      numberOfPasses: 5,
      price: 350,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.boulderm.com/pricing/membership',
      remarks: '',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 10,
      numberOfPasses: 1,
      price: 28,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderplusclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 10,
      numberOfPasses: 10,
      price: 200,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable at the counter',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.boulderplusclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 10,
      numberOfPasses: 0,
      price: 110,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 100,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderplusclimbing.com/membership-sign-up',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Youth Entry',
      passGroupId: 10,
      numberOfPasses: 1,
      price: 18,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 19',
      sharingPolicy: '',
      timeRestriction: 'Aperia: weekdays till 7pm\nChevrons: all day',
      validityPeriod: '',
      infoUrl: 'https://www.boulderplusclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Parent-Child',
      passGroupId: 10,
      numberOfPasses: 1,
      price: 35,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderplusclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Kids Entry',
      passGroupId: 10,
      numberOfPasses: 1,
      price: 16,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 13',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderplusclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 11,
      numberOfPasses: 1,
      price: 25,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderworld.com/rates',
      remarks: '',
    },
    {
      passName: 'Youth Entry',
      passGroupId: 11,
      numberOfPasses: 1,
      price: 18,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 18',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderworld.com/rates',
      remarks: '',
    },
    {
      passName: 'Adult-Child',
      passGroupId: 11,
      numberOfPasses: 1,
      price: 35,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 12',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.boulderworld.com/rates',
      remarks: '',
    },
    {
      passName: 'Adult Entry (Off-peak)',
      passGroupId: 11,
      numberOfPasses: 1,
      price: 16,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '9 AM to 5 PM | Weekdays',
      validityPeriod: '',
      infoUrl: 'https://www.boulderworld.com/rates',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 11,
      numberOfPasses: 5,
      price: 120,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable at the counter',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.boulderworld.com/rates',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 11,
      numberOfPasses: 10,
      price: 200,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable at the counter',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.boulderworld.com/rates',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 11,
      numberOfPasses: 0,
      price: 90,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 100,
      discountedInitiationFee: 50,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '9 AM to 5 PM | Weekdays',
      validityPeriod: '',
      infoUrl: 'https://www.boulderworld.com/rates',
      remarks: 'Locker - $5/month',
    },
    {
      passName: 'Subscription (Off-peak)',
      passGroupId: 11,
      numberOfPasses: 0,
      price: 50,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 100,
      discountedInitiationFee: 50,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '9 AM to 5 PM | Weekdays',
      validityPeriod: '',
      infoUrl: 'https://www.boulderworld.com/rates',
      remarks: 'Locker - $5/month',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 12,
      numberOfPasses: 1,
      price: 27,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: '',
    },
    {
      passName: 'Youth Entry',
      passGroupId: 12,
      numberOfPasses: 1,
      price: 21.6,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 18',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: '',
    },
    {
      passName: 'Adult-Child',
      passGroupId: 12,
      numberOfPasses: 1,
      price: 33.48,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 13',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: 'Children under 13 require supervising adult',
    },
    {
      passName: 'Child Add-On Entry',
      passGroupId: 12,
      numberOfPasses: 1,
      price: 19.44,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 13',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: 'Children under 13 require supervising adult',
    },
    {
      passName: 'Multipass',
      passGroupId: 12,
      numberOfPasses: 5,
      price: 113.4,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy:
        'Pass holder must be present at the counter, or have linked accounts',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 12,
      numberOfPasses: 10,
      price: 205.2,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy:
        'Pass holder must be present at the counter, or have linked accounts',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: '',
    },
    {
      passName: 'Adult-Child Multipass',
      passGroupId: 12,
      numberOfPasses: 5,
      price: 140.4,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 13',
      sharingPolicy:
        'Pass holder must be present at the counter, or have linked accounts',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: 'Children under 13 require supervising adult',
    },
    {
      passName: 'Adult-Child Multipass',
      passGroupId: 12,
      numberOfPasses: 10,
      price: 248.4,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 13',
      sharingPolicy:
        'Pass holder must be present at the counter, or have linked accounts',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: 'Children under 13 require supervising adult',
    },
    {
      passName: 'Adult Set',
      passGroupId: 12,
      numberOfPasses: 1,
      price: 37.8,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: 'Includes Shoe and Harness. First timers only',
    },
    {
      passName: 'Youth Set',
      passGroupId: 12,
      numberOfPasses: 1,
      price: 32.4,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 18',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: 'Includes Shoe and Harness. First timers only',
    },
    {
      passName: 'Adult-Child Set',
      passGroupId: 12,
      numberOfPasses: 1,
      price: 44.28,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 13',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks:
        'Children under 13 require supervising adult; Includes Shoe and Harness. First timers only',
    },
    {
      passName: 'Adult and 2 Children Set',
      passGroupId: 12,
      numberOfPasses: 1,
      price: 71.28,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 13',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks:
        'Children under 13 require supervising adult; Includes Shoe and Harness. First timers only',
    },
    {
      passName: 'Subscription',
      passGroupId: 12,
      numberOfPasses: 0,
      price: 194.4,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/entry-rates-updated',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription',
      passGroupId: 12,
      numberOfPasses: 0,
      price: 129.6,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 100,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/membership-rates-2023',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription',
      passGroupId: 13,
      numberOfPasses: 0,
      price: 102.6,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 100,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/membership-rates-2023',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription',
      passGroupId: 14,
      numberOfPasses: 0,
      price: 91.8,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 100,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/membership-rates-2023',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription',
      passGroupId: 15,
      numberOfPasses: 0,
      price: 97.2,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 100,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/membership-rates-2023',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription',
      passGroupId: 16,
      numberOfPasses: 0,
      price: 102.6,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 100,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.climbcentral.sg/membership-rates-2023',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 17,
      numberOfPasses: 1,
      price: 28,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://fitbloc.com/our-rates/',
      remarks: '',
    },
    {
      passName: 'Child Entry',
      passGroupId: 17,
      numberOfPasses: 1,
      price: 14,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '5-12',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://fitbloc.com/our-rates/',
      remarks: '1 child must be accompanied by 1 adult',
    },
    {
      passName: 'Multipass',
      passGroupId: 17,
      numberOfPasses: 3,
      price: 60,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Link accounts via Whatsapp',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://fitbloc.com/our-rates/',
      remarks: 'First timers only',
    },
    {
      passName: 'Multipass',
      passGroupId: 17,
      numberOfPasses: 10,
      price: 180,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Link accounts via Whatsapp',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://fitbloc.com/our-rates/',
      remarks: '',
    },
    {
      passName: 'Subscription ',
      passGroupId: 17,
      numberOfPasses: 0,
      price: 80,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 100,
      discountedInitiationFee: null,
      freezingFee: 15,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://fitbloc.com/product/unlimited-monthly-facilities-pass/',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 18,
      numberOfPasses: 1,
      price: 22,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: '',
    },
    {
      passName: 'Adult Entry (Off-peak)',
      passGroupId: 18,
      numberOfPasses: 1,
      price: 15,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction:
        'Weekdays (Tues- Fri), before 6 PM. Not available on\nPublic Holidays.',
      validityPeriod: '3 months from purchase',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 18,
      numberOfPasses: 5,
      price: 100,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 18,
      numberOfPasses: 10,
      price: 180,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: '',
    },
    {
      passName: 'Youth Entry',
      passGroupId: 18,
      numberOfPasses: 1,
      price: 15,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 18',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: '',
    },
    {
      passName: 'Youth (off peak)',
      passGroupId: 18,
      numberOfPasses: 1,
      price: 10,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 18',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: '',
    },
    {
      passName: 'Youth Multipass',
      passGroupId: 18,
      numberOfPasses: 5,
      price: 70,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 18',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: '',
    },
    {
      passName: 'Youth Multipass',
      passGroupId: 18,
      numberOfPasses: 10,
      price: 120,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 18',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: '',
    },
    {
      passName: 'Supervising Adult',
      passGroupId: 18,
      numberOfPasses: 1,
      price: 10,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 13',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: 'Children 12 and below require supervising adult',
    },
    {
      passName: 'Adult Set',
      passGroupId: 18,
      numberOfPasses: 1,
      price: 27,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: 'Includes Shoe and Harness. First timers only',
    },
    {
      passName: 'Youth Set',
      passGroupId: 18,
      numberOfPasses: 1,
      price: 20,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 18',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: 'Includes Shoe and Harness. First timers only',
    },
    {
      passName: 'Taster Session',
      passGroupId: 18,
      numberOfPasses: 1,
      price: 45,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by messaging on IG/FB but non-refundable',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.groundupsg.com/rates',
      remarks: 'Includes Shoe and Harness, max 4 pax, notify a week in advance',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 19,
      numberOfPasses: 1,
      price: 19,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.kineticsclimbing.com.sg/opening-hours-rates',
      remarks:
        'Adult superivision is mandatory for kids (5 - 12 yrs old) who are bouldering on their own',
    },
    {
      passName: 'Student Entry',
      passGroupId: 19,
      numberOfPasses: 1,
      price: 15,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 22',
      sharingPolicy: '',
      timeRestriction: 'Leave by 7pm; not available on weekends and PH',
      validityPeriod: '',
      infoUrl: 'https://www.kineticsclimbing.com.sg/opening-hours-rates',
      remarks:
        'Adult superivision is mandatory for kids (5 - 12 yrs old) who are bouldering on their own',
    },
    {
      passName: 'Multipass',
      passGroupId: 19,
      numberOfPasses: 5,
      price: 85,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Transferable ',
      timeRestriction: '',
      validityPeriod: '12 months',
      infoUrl: 'https://www.kineticsclimbing.com.sg/opening-hours-rates',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 19,
      numberOfPasses: 10,
      price: 150,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Transferable ',
      timeRestriction: '',
      validityPeriod: '12 months',
      infoUrl: 'https://www.kineticsclimbing.com.sg/opening-hours-rates',
      remarks: '',
    },
    {
      passName: 'Subscription ',
      passGroupId: 19,
      numberOfPasses: 0,
      price: 110,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.kineticsclimbing.com.sg/opening-hours-rates',
      remarks: '$250 for the first 2 months. No freezing',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 20,
      numberOfPasses: 1,
      price: 24,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.lighthouseclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Youth Entry',
      passGroupId: 20,
      numberOfPasses: 1,
      price: 18,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 19',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.lighthouseclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Senior Citizen Entry',
      passGroupId: 20,
      numberOfPasses: 1,
      price: 18,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '> 54',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.lighthouseclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Child Entry',
      passGroupId: 20,
      numberOfPasses: 1,
      price: 15,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 13',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.lighthouseclimbing.com/rates',
      remarks: 'All children have to be supervised by a paying adult.',
    },
    {
      passName: 'Adult-Child Entry',
      passGroupId: 20,
      numberOfPasses: 1,
      price: 35,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 13',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.lighthouseclimbing.com/rates',
      remarks: 'All children have to be supervised by a paying adult.',
    },
    {
      passName: 'Multipass',
      passGroupId: 20,
      numberOfPasses: 5,
      price: 110,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable',
      timeRestriction: '',
      validityPeriod: '6 months',
      infoUrl: 'https://www.lighthouseclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 20,
      numberOfPasses: 10,
      price: 200,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable',
      timeRestriction: '',
      validityPeriod: '12 months',
      infoUrl: 'https://www.lighthouseclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 20,
      numberOfPasses: 0,
      price: 100,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 68,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.lighthouseclimbing.com/rates',
      remarks: '',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 21,
      numberOfPasses: 1,
      price: 26,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://originboulder.sg/price-list/',
      remarks: '',
    },
    {
      passName: 'Youth Entry',
      passGroupId: 21,
      numberOfPasses: 1,
      price: 18,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '13-18',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://originboulder.sg/price-list/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 21,
      numberOfPasses: 5,
      price: 120,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable',
      timeRestriction: '',
      validityPeriod: '3 months',
      infoUrl: 'https://originboulder.sg/price-list/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 21,
      numberOfPasses: 10,
      price: 200,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable',
      timeRestriction: '',
      validityPeriod: '6 months',
      infoUrl: 'https://originboulder.sg/price-list/',
      remarks: '',
    },
    {
      passName: 'Multipass (Off-peak)',
      passGroupId: 21,
      numberOfPasses: 5,
      price: 90,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable',
      timeRestriction: 'Weekdays opening till 6.45pm',
      validityPeriod: '3 months',
      infoUrl: 'https://originboulder.sg/price-list/',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 21,
      numberOfPasses: 4,
      price: 72,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: 48,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://originboulder.sg/price-list/',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Subscription',
      passGroupId: 21,
      numberOfPasses: 0,
      price: 148,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: 88,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://originboulder.sg/price-list/',
      remarks: 'With subscription perks',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 22,
      numberOfPasses: 1,
      price: 18,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://oyeyoboulderhome.com/collections/all',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 22,
      numberOfPasses: 5,
      price: 80,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy:
        'Shareable by providing contact details of multi-pass holder at counter',
      timeRestriction: '',
      validityPeriod: '6 months',
      infoUrl: 'https://oyeyoboulderhome.com/collections/all',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 22,
      numberOfPasses: 10,
      price: 140,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy:
        'Shareable by providing contact details of multi-pass holder at counter',
      timeRestriction: '',
      validityPeriod: '6 months',
      infoUrl: 'https://oyeyoboulderhome.com/collections/all',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 22,
      numberOfPasses: 20,
      price: 240,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy:
        'Shareable by providing contact details of multi-pass holder at counter',
      timeRestriction: '',
      validityPeriod: '12 months',
      infoUrl: 'https://oyeyoboulderhome.com/collections/all',
      remarks: '',
    },
    {
      passName: 'Full Day Experience',
      passGroupId: 23,
      numberOfPasses: 1,
      price: 35,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.projectsend.co/rates',
      remarks: '',
    },
    {
      passName: 'First Timer Class',
      passGroupId: 23,
      numberOfPasses: 1,
      price: 40,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.projectsend.co/rates',
      remarks: 'First timers only.',
    },
    {
      passName: 'Parent-Child',
      passGroupId: 23,
      numberOfPasses: 1,
      price: 40,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '7-12',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.projectsend.co/rates',
      remarks: '',
    },
    {
      passName: '1 Week Binge Climb',
      passGroupId: 23,
      numberOfPasses: 0,
      price: 50,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.projectsend.co/rates',
      remarks: '',
    },
    {
      passName: 'Subscription',
      passGroupId: 23,
      numberOfPasses: 0,
      price: 149,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.projectsend.co/rates',
      remarks: 'Unlimited classes',
    },
    {
      passName: 'Subscription (Student)',
      passGroupId: 23,
      numberOfPasses: 0,
      price: 75,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 22',
      sharingPolicy: '',
      timeRestriction: 'Off-Peak (10am-5pm weekdays)',
      validityPeriod: '',
      infoUrl: 'https://www.projectsend.co/rates',
      remarks: 'Unlimited classes',
    },
    {
      passName: '100 Credits ',
      passGroupId: 23,
      numberOfPasses: 10,
      price: 240,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by pre-linking via email, then at the counter',
      timeRestriction: '',
      validityPeriod: '3 months',
      infoUrl: 'https://www.projectsend.co/rates',
      remarks: '10 credits per climb, 15 credits per class + climb',
    },
    {
      passName: '200 Credits',
      passGroupId: 23,
      numberOfPasses: 20,
      price: 440,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by pre-linking via email, then at the counter',
      timeRestriction: '',
      validityPeriod: '6 months',
      infoUrl: 'https://www.projectsend.co/rates',
      remarks: '10 credits per climb, 15 credits per class + climb',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 24,
      numberOfPasses: 1,
      price: 28,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '',
    },
    {
      passName: 'Youth Entry',
      passGroupId: 24,
      numberOfPasses: 1,
      price: 16,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 21',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '',
    },
    {
      passName: 'Supervising Adult',
      passGroupId: 24,
      numberOfPasses: 1,
      price: 10,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 10',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: 'Adult supervision is required for climbers below age 10',
    },
    {
      passName: 'Multipass',
      passGroupId: 24,
      numberOfPasses: 5,
      price: 130,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable',
      timeRestriction: '',
      validityPeriod: '6 months',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 24,
      numberOfPasses: 10,
      price: 220,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable',
      timeRestriction: '',
      validityPeriod: '6 months',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '',
    },
    {
      passName: 'Adult Entry (Member)',
      passGroupId: 24,
      numberOfPasses: 1,
      price: 22,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '',
    },
    {
      passName: 'Youth Entry (Member)',
      passGroupId: 24,
      numberOfPasses: 1,
      price: 13,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 21',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '',
    },
    {
      passName: 'Multipass (Member)',
      passGroupId: 24,
      numberOfPasses: 6,
      price: 130,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable',
      timeRestriction: '',
      validityPeriod: '6 months',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '+1 pass for members',
    },
    {
      passName: 'Multipass (Member)',
      passGroupId: 24,
      numberOfPasses: 11,
      price: 220,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable',
      timeRestriction: '',
      validityPeriod: '6 months',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '+1 pass for members',
    },
    {
      passName: 'Subscription',
      passGroupId: 24,
      numberOfPasses: 0,
      price: 100,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '',
    },
    {
      passName: '3-Month Subscription',
      passGroupId: 24,
      numberOfPasses: 0,
      price: 285,
      discountedPrice: null,
      paymentFrequency: '/3 months',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '',
    },
    {
      passName: 'Subscription (Youth)',
      passGroupId: 24,
      numberOfPasses: 0,
      price: 60,
      discountedPrice: null,
      paymentFrequency: '/month',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 21',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '',
    },
    {
      passName: '3-Month Subscription (Youth)',
      passGroupId: 24,
      numberOfPasses: 0,
      price: 165,
      discountedPrice: null,
      paymentFrequency: '/3 months',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 21',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl:
        'https://t-hall.sg/wp-content/uploads/2022/09/THALL_PriceList_1Oct2022.pdf',
      remarks: '',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 25,
      numberOfPasses: 1,
      price: 17,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '> 19',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.therockschool.sg/entry-pass/',
      remarks: '',
    },
    {
      passName: 'Youth Entry',
      passGroupId: 25,
      numberOfPasses: 1,
      price: 15,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 19',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.therockschool.sg/entry-pass/',
      remarks: '',
    },
    {
      passName: 'Supervising Adult',
      passGroupId: 25,
      numberOfPasses: 1,
      price: 10,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.therockschool.sg/entry-pass/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 25,
      numberOfPasses: 5,
      price: 80,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by contacting gym via Whatsapp',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl: 'https://www.therockschool.sg/entry-pass/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 25,
      numberOfPasses: 10,
      price: 150,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by contacting gym via Whatsapp',
      timeRestriction: '',
      validityPeriod: '6 months from purchase',
      infoUrl: 'https://www.therockschool.sg/entry-pass/',
      remarks: '',
    },
    {
      passName: 'Multipass',
      passGroupId: 25,
      numberOfPasses: 30,
      price: 390,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by contacting gym via Whatsapp',
      timeRestriction: '',
      validityPeriod: '12 months from purchase',
      infoUrl: 'https://www.therockschool.sg/entry-pass/',
      remarks: '',
    },
    {
      passName: 'Subscription (Individual)',
      passGroupId: 25,
      numberOfPasses: 0,
      price: 59,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 80,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.therockschool.sg/entry-pass/',
      remarks: 'Free rental gear. Priority for events.',
    },
    {
      passName: 'Subscription (Family Pair)',
      passGroupId: 25,
      numberOfPasses: 0,
      price: 98,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: 80,
      discountedInitiationFee: null,
      freezingFee: 10,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://www.therockschool.sg/entry-pass/',
      remarks: 'Free rental gear. Priority for events.',
    },
    {
      passName: 'Adult Entry',
      passGroupId: 26,
      numberOfPasses: 1,
      price: 17,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://zvertigobouldergym.wixsite.com/zvert/rates',
      remarks: '',
    },
    {
      passName: 'Youth Entry',
      passGroupId: 26,
      numberOfPasses: 1,
      price: 12,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 19',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://zvertigobouldergym.wixsite.com/zvert/rates',
      remarks: '',
    },
    {
      passName: 'Child Entry',
      passGroupId: 26,
      numberOfPasses: 1,
      price: 9,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '< 14',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://zvertigobouldergym.wixsite.com/zvert/rates',
      remarks: 'Must be accompanied by an adult',
    },
    {
      passName: 'Multipass',
      passGroupId: 26,
      numberOfPasses: 10,
      price: 140,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by providing gym ID, but not transferable',
      timeRestriction: '',
      validityPeriod: '6 months ',
      infoUrl: 'https://zvertigobouldergym.wixsite.com/zvert/rates',
      remarks: '',
    },
    {
      passName: '3-Month Subscription (Opening Promo)',
      passGroupId: 26,
      numberOfPasses: 0,
      price: 300,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: '',
      timeRestriction: '',
      validityPeriod: '',
      infoUrl: 'https://zvertigobouldergym.wixsite.com/zvert/rates',
      remarks: '',
    },
    {
      passName: 'Guided Boulder Class (Kids) (Opening Promo)',
      passGroupId: 27,
      numberOfPasses: 1,
      price: 35,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '2-6',
      sharingPolicy: 'Shareable by group booking or linking account',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl:
        'https://www.climbt3.sg/class/25832fd1-d53d-4e1b-a116-259ebd498cbf',
      remarks: '',
    },
    {
      passName: 'Guided High Wall Class (Opening Promo)',
      passGroupId: 27,
      numberOfPasses: 1,
      price: 28,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '> 3',
      sharingPolicy: 'Shareable by group booking or linking account',
      timeRestriction: '',
      validityPeriod: '1 month from purchase',
      infoUrl:
        'https://www.climbt3.sg/class/f8a94b64-dda8-4fe2-80de-f895f3a8b1fb',
      remarks: '',
    },
    {
      passName: '5x Guided High Wall Class (Opening Promo)',
      passGroupId: 27,
      numberOfPasses: 5,
      price: 115,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by group booking or linking account',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl:
        'https://www.climbt3.sg/class/f8a94b64-dda8-4fe2-80de-f895f3a8b1fb',
      remarks: '',
    },
    {
      passName: 'Adult Entry (Opening Promo)',
      passGroupId: 27,
      numberOfPasses: 1,
      price: 17,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by group booking or linking account',
      timeRestriction: '',
      validityPeriod: '1 month from purchase',
      infoUrl:
        'https://www.climbt3.sg/class/15b4340d-3518-498b-8e3b-9e4782cb0077',
      remarks: '',
    },
    {
      passName: 'Multipass (Opening Promo)',
      passGroupId: 27,
      numberOfPasses: 5,
      price: 80,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by group booking or linking account',
      timeRestriction: '',
      validityPeriod: '3 months from purchase',
      infoUrl:
        'https://www.climbt3.sg/class/15b4340d-3518-498b-8e3b-9e4782cb0077',
      remarks: '',
    },
    {
      passName: 'Supervising Adult (Opening Promo)',
      passGroupId: 27,
      numberOfPasses: 1,
      price: 10,
      discountedPrice: null,
      paymentFrequency: '',
      initiationFee: null,
      discountedInitiationFee: null,
      freezingFee: null,
      ageRestriction: '',
      sharingPolicy: 'Shareable by group booking or linking account',
      timeRestriction: '',
      validityPeriod: '1 month from purchase',
      infoUrl: 'https://www.climbt3.sg/package?tab=',
      remarks: '',
    },
  ]);

  const gymGroupsData = [
    { id: 18, passGroupId: 1 },
    { id: 3, passGroupId: 4 },
    { id: 4, passGroupId: 7 },
    { id: 5, passGroupId: 9 },
    { id: 6, passGroupId: 10 },
    { id: 8, passGroupId: 12 },
    { id: 9, passGroupId: 17 },
  ];

  // await Promise.all(
  //   gymGroupsData.map((row) => {
  //     return knex('gymGroups').update(row).where('id', row.id);
  //   }),
  // );

  // doesn't work as insert requires each item to fulfill all the notNullable()s
  // await knex('gymGroups').insert(gymGroupsData).onConflict('id').merge()

  for (const row of gymGroupsData) {
    await knex('gymGroups').update(row).where('id', row.id);
  }

  const gymsData = [
    { id: 2, passGroupId: 2 },
    { id: 3, passGroupId: 3 },
    { id: 4, passGroupId: 5 },
    { id: 5, passGroupId: 6 },
    // { id: 6, passGroupId: 8 },
    { id: 16, passGroupId: 11 },
    { id: 17, passGroupId: 13 },
    { id: 18, passGroupId: 14 },
    { id: 19, passGroupId: 15 },
    { id: 20, passGroupId: 16 },
    { id: 23, passGroupId: 18 },
    { id: 24, passGroupId: 19 },
    { id: 25, passGroupId: 20 },
    { id: 26, passGroupId: 21 },
    { id: 27, passGroupId: 22 },
    { id: 28, passGroupId: 23 },
    { id: 29, passGroupId: 24 },
    { id: 30, passGroupId: 25 },
    { id: 32, passGroupId: 26 },
    { id: 34, passGroupId: 27 },
  ];

  // await Promise.all(
  //   gymsData.map((row) => {
  //     return knex('gyms').update(row).where('id', row.id);
  //   }),
  // );

  // await knex('gyms').insert(gymsData).onConflict('id').merge()

  for (const row of gymsData) {
    await knex('gyms').update(row).where('id', row.id);
  }
}
